/*
Constants defined for alert actions
*/

export const appActionsConstants = {
  SHOW_MESSAGE_SNACK_BOTTOM: "app/SHOW_MESSAGE_SNACK_BOTTOM",
  HIDE_MESSAGE_SNACK_BOTTOM: "app/HIDE_MESSAGE_SNACK_BOTTOM",
  FETCH_SUPPORTED_LOCALE_REQUEST: "app/FETCH_SUPPORTED_LOCALE_REQUEST",
  FETCH_SUPPORTED_LOCALE_SUCCESS: "app/FETCH_SUPPORTED_LOCALE_SUCCESS"
};
